import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repository.
*/
`;

const prod = process.argv[2] === "production";

const NODE_BUILTINS = [
    "assert", "async_hooks", "buffer", "child_process", "cluster", "console",
    "constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
    "events", "fs", "http", "http2", "https", "inspector", "module", "net",
    "os", "path", "perf_hooks", "process", "punycode", "querystring",
    "readline", "repl", "stream", "string_decoder", "sys", "timers", "tls",
    "trace_events", "tty", "url", "util", "v8", "vm", "wasi", "worker_threads",
    "zlib",
].flatMap((m) => [m, `node:${m}`]);

/**
 * Copies the built plugin into an Obsidian vault so the running app picks it up.
 * Override the target with OBSYNC_DEPLOY_DIR, or set it to "" to skip deploying.
 */
const deployDir =
    process.env.OBSYNC_DEPLOY_DIR ?? "F:/_Workspace/Plugin-Test/.obsidian/plugins/obsync";

const ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

const deployPlugin = {
    name: "deploy-to-vault",
    setup(build) {
        build.onEnd((result) => {
            if (result.errors.length > 0) return;
            if (!deployDir) {
                console.log("[deploy] skipped (OBSYNC_DEPLOY_DIR is empty)");
                return;
            }
            try {
                fs.mkdirSync(deployDir, { recursive: true });
                for (const file of ARTIFACTS) {
                    if (fs.existsSync(file)) {
                        fs.copyFileSync(file, path.join(deployDir, file));
                    }
                }
                console.log(`[deploy] ${ARTIFACTS.join(", ")} -> ${deployDir}`);
            } catch (err) {
                // A missing vault must never break the build.
                console.warn(`[deploy] skipped: ${err.message}`);
            }
        });
    },
};

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "moment",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...NODE_BUILTINS,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    platform: "browser",
    minify: prod,
    outfile: "main.js",
    plugins: [deployPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
