import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repository.
*/
`;

const prod = process.argv[2] === "production";

const NODE_BUILTINS = [
    "assert", "async_hooks", "buffer", "child_process", "cluster", "console",
    "constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
    "events", "fs", "http", "http2", "https", "inspector", "module", "net",
    "os", "path", "perf_hooks", "process", "punycode", "querystring",
    "readline", "repl", "stream", "string_decoder", "sys", "timers", "tls",
    "trace_events", "tty", "url", "util", "v8", "vm", "wasi", "worker_threads",
    "zlib",
].flatMap((m) => [m, `node:${m}`]);

/**
 * Copies the built plugin into Obsidian vault(s) so the running app picks it up.
 *
 * `OBSYNC_DEPLOY_DIR` 接受**多个**目录，用 `;` 分隔 —— 一次构建就能同时更新测试库与
 * 真实库（`pnpm build:both` 就是这么做的）。设成空串则整个跳过部署。
 *
 * 分隔符固定用 `;` 而**不是** `path.delimiter`：后者在 POSIX 上是 `:`，
 * 而 Windows 盘符 `F:/…` 里本来就带冒号 —— 用它会把一份配置切碎。
 */
const DEFAULT_DEPLOY_DIRS = ["F:/_Workspace/Plugin-Test/.obsidian/plugins/synchub"];

const deployDirs = (process.env.OBSYNC_DEPLOY_DIR ?? DEFAULT_DEPLOY_DIRS.join(";"))
    .split(";")
    .map((dir) => dir.trim())
    .filter((dir) => dir.length > 0);

const ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

const deployPlugin = {
    name: "deploy-to-vault",
    setup(build) {
        build.onEnd((result) => {
            if (result.errors.length > 0) return;
            if (deployDirs.length === 0) {
                console.log("[deploy] skipped (OBSYNC_DEPLOY_DIR is empty)");
                return;
            }
            // 每个目标各自 try：一个库写不进去（不存在、被占用）不该连累另一个。
            for (const dir of deployDirs) {
                try {
                    fs.mkdirSync(dir, { recursive: true });
                    for (const file of ARTIFACTS) {
                        if (fs.existsSync(file)) {
                            fs.copyFileSync(file, path.join(dir, file));
                        }
                    }
                    console.log(`[deploy] ${ARTIFACTS.join(", ")} -> ${dir}`);
                } catch (err) {
                    // A missing vault must never break the build.
                    console.warn(`[deploy] skipped ${dir}: ${err.message}`);
                }
            }
        });
    },
};

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "moment",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...NODE_BUILTINS,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    platform: "browser",
    minify: prod,
    outfile: "main.js",
    plugins: [deployPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
